using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MovieProject.API.Data;

namespace MovieProject.API.Controllers
{
    [Route("[controller]")]
    [ApiController]
    [Authorize]
    public class MovieController : ControllerBase
    {
        private readonly MovieDbContext _movieContext;

        public MovieController(MovieDbContext temp) => _movieContext = temp;

        [HttpGet("RecMoviesTemp")]
        public IActionResult GetMovies([FromQuery] List<string>? genres = null)
        {
            var query = _movieContext.Movies.AsQueryable();

            if (genres != null && genres.Any())
            {
                List<int> numGenres = _movieContext.Genres
                    .Where(g => genres.Contains(g.Name))
                    .Select(g => g.Code)
                    .ToList();


                var movieGenres = _movieContext.MovieGenres.ToList();

                var showIds = movieGenres.Where(m => numGenres.Contains(m.GenreCode)).Select(m => m.ShowId).ToList();

                query = query.Where(m => showIds.Contains(m.ShowId));
            }

            var movies = query
                .Include(m => m.MovieGenres)
                .ThenInclude(mg => mg.Genre)
                .ToList();

            return Ok(movies);
        }

        // New endpoint to fetch details for a single movie using its unique ID.
        [HttpGet("Details/{show_id}")]
        public IActionResult GetMovieDetails(string show_id)
        {
            var movie = _movieContext.Movies
                .Include(m => m.MovieGenres)
                .ThenInclude(mg => mg.Genre)
                .FirstOrDefault(m => m.ShowId == show_id); 

            if (movie == null)
            {
                return NotFound(new { message = "Movie not found" });
            }
            return Ok(movie);
        }

        [HttpPost("AddUser")]
        [AllowAnonymous]
        public IActionResult AddUser([FromBody] User newUser)
        {
            // Validate the model
            if (!ModelState.IsValid)
            {
                // Get all error messages to return to the client
                var errors = ModelState.Values.SelectMany(v => v.Errors)
                                              .Select(e => e.ErrorMessage);
                return BadRequest(new { Message = "Invalid user data.", Errors = errors });
            }

            // Ensure that if the client sends a default UserId (0) it is treated as the default value 
            // and not explicitly inserted into the database.
            // The [DatabaseGenerated(DatabaseGeneratedOption.Identity)] attribute on the UserId property tells EF Core 
            // that this column's value will be generated by the database.
            if (newUser.UserId != 0)
            {
                // Optionally, you can warn or set it back to the default value.
                newUser.UserId = 0;
            }

            try
            {
                _movieContext.Users.Add(newUser);
                _movieContext.SaveChanges();
            }
            catch (Exception ex)
            {
                // Log the exception if needed, then return a 500 error with details
                return StatusCode(500, new { Message = "An error occurred while adding the user.", Error = ex.Message });
            }

            // Return the newly created user (the UserId will now be the value generated by the database)
            return Ok(newUser);
        }



        [HttpGet("ContentRecommendations")]
        public IActionResult GetContentRecomendation(string movieName)
        {
            var record = _movieContext.MovieRecomendation
                            .FirstOrDefault(c => c.movieName.Equals(movieName, StringComparison.OrdinalIgnoreCase));

            if (record == null)
            {
                return NotFound(new { message = $"No recommendations found for movie: {movieName}" });
            }

            var recommendations = new List<string>
            {
                record.Recommendation1,
                record.Recommendation2,
                record.Recommendation3,
                record.Recommendation4,
                record.Recommendation5
            }
            .Where(r => !string.IsNullOrEmpty(r))
            .ToList();

            if (!recommendations.Any())
            {
                return NotFound(new { message = $"No recommendations found for movie: {movieName}" });
            }

            return Ok(recommendations);
        }

        [HttpGet("CollaborativeRecommendations")]
        public IActionResult GetCollaborativeRecommendations(string movieName)
        {
            var record = _movieContext.MovieRecomendation
                            .FirstOrDefault(c => c.movieName.Equals(movieName, StringComparison.OrdinalIgnoreCase));

            if (record == null)
            {
                return NotFound(new { message = $"No recommendations found for movie: {movieName}" });
            }

            var recommendations = new List<string>
            {
                record.Recommendation1,
                record.Recommendation2,
                record.Recommendation3,
                record.Recommendation4,
                record.Recommendation5
            }
            .Where(r => !string.IsNullOrEmpty(r))
            .ToList();

            if (!recommendations.Any())
            {
                return NotFound(new { message = $"No recommendations found for movie: {movieName}" });
            }

            return Ok(recommendations);
        }

        [HttpGet("Genres")]
        public IActionResult GetGenres()
        {
            var genres = _movieContext.Genres
                .Select(m => m.Name)
                .ToList();
            return Ok(genres);
        }

[Authorize(Roles = "Admin")]
[HttpGet("AllMovies")]
public IActionResult GetProjects(int pageSize = 10, int pageNum = 1, string searchQuery = "", [FromQuery] List<string>? projectTypes = null)
{
    var query = _movieContext.Movies.AsQueryable();

    if (projectTypes != null && projectTypes.Any())
{
    foreach (var genre in projectTypes)
    {
        switch (genre.ToLower())
        {
            case "action":
                query = query.Where(m => m.Action == 1);
                break;
            case "adventure":
                query = query.Where(m => m.Adventure == 1);
                break;
            case "animeseriesinternationaltvshows":
                query = query.Where(m => m.AnimeSeriesInternationalTvShows == 1);
                break;
            case "britishtvshowsdocuseriesinternationaltvshows":
                query = query.Where(m => m.BritishTvShowsDocuseriesInternationalTvShows == 1);
                break;
            case "children":
                query = query.Where(m => m.Children == 1);
                break;
            case "comedies":
                query = query.Where(m => m.Comedies == 1);
                break;
            case "comediesdramasinternationalmovies":
                query = query.Where(m => m.ComediesDramasInternationalMovies == 1);
                break;
            case "comediesinternationalmovies":
                query = query.Where(m => m.ComediesInternationalMovies == 1);
                break;
            case "comediesromanticmovies":
                query = query.Where(m => m.ComediesRomanticMovies == 1);
                break;
            case "crimetvshowsdocuseries":
                query = query.Where(m => m.CrimeTvShowsDocuseries == 1);
                break;
            case "documentaries":
                query = query.Where(m => m.Documentaries == 1);
                break;
            case "documentariesinternationalmovies":
                query = query.Where(m => m.DocumentariesInternationalMovies == 1);
                break;
            case "docuseries":
                query = query.Where(m => m.Docuseries == 1);
                break;
            case "dramas":
                query = query.Where(m => m.Dramas == 1);
                break;
            case "dramasinternationalmovies":
                query = query.Where(m => m.DramasInternationalMovies == 1);
                break;
            case "dramasromanticmovies":
                query = query.Where(m => m.DramasRomanticMovies == 1);
                break;
            case "familymovies":
                query = query.Where(m => m.FamilyMovies == 1);
                break;
            case "fantasy":
                query = query.Where(m => m.Fantasy == 1);
                break;
            case "horrormovies":
                query = query.Where(m => m.HorrorMovies == 1);
                break;
            case "internationalmoviesthrillers":
                query = query.Where(m => m.InternationalMoviesThrillers == 1);
                break;
            case "internationaltvshowsromantictvshows":
                query = query.Where(m => m.InternationalTvShowsRomanticTvShowsTvDramas == 1);
                break;
            case "kidstv":
                query = query.Where(m => m.KidsTV == 1);
                break;
            case "languagetvshows":
                query = query.Where(m => m.LanguageTvShows == 1);
                break;
            case "musicals":
                query = query.Where(m => m.Musicals == 1);
                break;
            case "naturetv":
                query = query.Where(m => m.NatureTv == 1);
                break;
            case "realitytv":
                query = query.Where(m => m.RealityTv == 1);
                break;
            case "spirituality":
                query = query.Where(m => m.Spirituality == 1);
                break;
            case "tvaction":
                query = query.Where(m => m.TvAction == 1);
                break;
            case "tvcomedies":
                query = query.Where(m => m.TvComedies == 1);
                break;
            case "tvdramas":
                query = query.Where(m => m.TvDramas == 1);
                break;
            case "talkshowstvcomedies":
                query = query.Where(m => m.TalkShowsTvComedies == 1);
                break;
            case "thrillers":
                query = query.Where(m => m.Thrillers == 1);
                break;
            default:
                break;
        }
    }
}


    if (!string.IsNullOrWhiteSpace(searchQuery))
    {
        query = query.Where(m => m.Title.ToLower().Contains(searchQuery.ToLower()));
    }

    var totalNumMovies = query.Count();

    var movies = query
        .Skip((pageNum - 1) * pageSize)
        .Take(pageSize)
        .ToList();

    var result = new
    {
        Movies = movies,
        TotalNumMovies = totalNumMovies
    };

    return Ok(result);
}


        [HttpGet("GetMovieTypes")]
        public IActionResult GetProjectTypes()
        {
            var projectTypes = _movieContext.Movies
                .Select(p => p.Genres)
                .Distinct()
                .ToList();

            return Ok(projectTypes);
        }

[HttpPost("AddMovie")]
[Authorize(Roles = "Admin")]
public IActionResult AddMovie([FromBody] Movie newMovie)
{
    if (newMovie == null)
    {
        return BadRequest("Movie data is null.");
    }

    if (!ModelState.IsValid)
    {
        var errors = ModelState.Values.SelectMany(v => v.Errors)
                                      .Select(e => e.ErrorMessage);
        return BadRequest(new { Message = "Invalid movie data", Errors = errors });
    }
    
    try
    {
        // Query the maximum numeric part from ShowId.
        // This assumes your ShowId always starts with an "s" followed by a number.
        int maxId = _movieContext.Movies
    .AsEnumerable()
    .Select(m => int.Parse(m.ShowId.Substring(1)))
    .DefaultIfEmpty(0)
    .Max();
        
        // Generate a new ShowId by incrementing the max value.
        newMovie.ShowId = "s" + (maxId + 1).ToString();

        _movieContext.Movies.Add(newMovie);
        _movieContext.SaveChanges();
        return Ok(newMovie);
    }
    catch (Exception ex)
    {
        return StatusCode(500, $"Internal server error: {ex.Message}");
    }
}


        [Authorize(Roles = "Admin")]
        [HttpPut("UpdateMovie/{show_id}")]
        public IActionResult UpdateProject(string show_id, [FromBody] MovieUpdateDTO updatedMovie)
        {
            var existingMovie = _movieContext.Movies.Find(show_id);

            if (existingMovie == null)
            {
                return NotFound();
            }

            existingMovie.Title = updatedMovie.Title;
            existingMovie.Director = updatedMovie.Director;
            existingMovie.Cast = updatedMovie.Cast;
            existingMovie.Country = updatedMovie.Country;
            existingMovie.release_year = updatedMovie.ReleaseYear;
            existingMovie.Rating = updatedMovie.Rating;
            existingMovie.Duration = updatedMovie.Duration;
            existingMovie.Description = updatedMovie.Description;

            existingMovie.Action = 0;
            existingMovie.Adventure = 0;
            existingMovie.AnimeSeriesInternationalTvShows = 0;
            existingMovie.BritishTvShowsDocuseriesInternationalTvShows = 0;
            existingMovie.Children = 0;
            existingMovie.Comedies = 0;
            existingMovie.ComediesDramasInternationalMovies = 0;
            existingMovie.ComediesInternationalMovies = 0;
            existingMovie.ComediesRomanticMovies = 0;
            existingMovie.CrimeTvShowsDocuseries = 0;
            existingMovie.Documentaries = 0;
            existingMovie.DocumentariesInternationalMovies = 0;
            existingMovie.Docuseries = 0;
            existingMovie.Dramas = 0;
            existingMovie.DramasInternationalMovies = 0;
            existingMovie.DramasRomanticMovies = 0;
            existingMovie.FamilyMovies = 0;
            existingMovie.Fantasy = 0;
            existingMovie.HorrorMovies = 0;
            existingMovie.InternationalMoviesThrillers = 0;
            existingMovie.InternationalTvShowsRomanticTvShowsTvDramas = 0;
            existingMovie.KidsTV = 0;
            existingMovie.LanguageTvShows = 0;
            existingMovie.Musicals = 0;
            existingMovie.NatureTv = 0;
            existingMovie.RealityTv = 0;
            existingMovie.Spirituality = 0;
            existingMovie.TvAction = 0;
            existingMovie.TvComedies = 0;
            existingMovie.TvDramas = 0;
            existingMovie.TalkShowsTvComedies = 0;
            existingMovie.Thrillers = 0;

            foreach (var genre in updatedMovie.Genres)
            {
                switch (genre)
                {
                    case "Action": existingMovie.Action = 1; break;
                    case "Adventure": existingMovie.Adventure = 1; break;
                    case "Anime Series International TV Shows": existingMovie.AnimeSeriesInternationalTvShows = 1; break;
                    case "British TV Shows Docuseries International TV Shows": existingMovie.BritishTvShowsDocuseriesInternationalTvShows = 1; break;
                    case "Children": existingMovie.Children = 1; break;
                    case "Comedies": existingMovie.Comedies = 1; break;
                    case "Comedies Dramas International Movies": existingMovie.ComediesDramasInternationalMovies = 1; break;
                    case "Comedies International Movies": existingMovie.ComediesInternationalMovies = 1; break;
                    case "Comedies Romantic Movies": existingMovie.ComediesRomanticMovies = 1; break;
                    case "Crime TV Shows Docuseries": existingMovie.CrimeTvShowsDocuseries = 1; break;
                    case "Documentaries": existingMovie.Documentaries = 1; break;
                    case "Documentaries International Movies": existingMovie.DocumentariesInternationalMovies = 1; break;
                    case "Docuseries": existingMovie.Docuseries = 1; break;
                    case "Dramas": existingMovie.Dramas = 1; break;
                    case "Dramas International Movies": existingMovie.DramasInternationalMovies = 1; break;
                    case "Dramas Romantic Movies": existingMovie.DramasRomanticMovies = 1; break;
                    case "Family Movies": existingMovie.FamilyMovies = 1; break;
                    case "Fantasy": existingMovie.Fantasy = 1; break;
                    case "Horror Movies": existingMovie.HorrorMovies = 1; break;
                    case "International Movies Thrillers": existingMovie.InternationalMoviesThrillers = 1; break;
                    case "International TV Shows Romantic TV Shows": existingMovie.InternationalTvShowsRomanticTvShowsTvDramas = 1; break;
                    case "Kids' TV": existingMovie.KidsTV = 1; break;
                    case "Language TV Shows": existingMovie.LanguageTvShows = 1; break;
                    case "Musicals": existingMovie.Musicals = 1; break;
                    case "Nature TV": existingMovie.NatureTv = 1; break;
                    case "Reality TV": existingMovie.RealityTv = 1; break;
                    case "Spirituality": existingMovie.Spirituality = 1; break;
                    case "TV Action": existingMovie.TvAction = 1; break;
                    case "TV Comedies": existingMovie.TvComedies = 1; break;
                    case "TV Dramas": existingMovie.TvDramas = 1; break;
                    case "Talk Shows TV Comedies": existingMovie.TalkShowsTvComedies = 1; break;
                    case "Thrillers": existingMovie.Thrillers = 1; break;
                }
            }

            _movieContext.SaveChanges();

            return Ok(existingMovie);
        }
        [Authorize(Roles = "Admin")]
        [HttpDelete("DeleteMovie/{show_id}")]
        public IActionResult DeleteMovie(string show_id)
        {
            var movie = _movieContext.Movies.Find(show_id);

            if (movie == null)
            {
                return NotFound(new { message = "Movie not found" });
            }

            _movieContext.Movies.Remove(movie);
            _movieContext.SaveChanges();

            return NoContent();
        }
    }
}